#pragma config(Sensor, dgtl1,  bump,           sensorDigitalIn)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
task main()
{
	bool activated = false;
	bool reverse = false;
	
	while(true){
		while(SensorValue[bump] == 0 && !reverse){
			activated = true;
		}
		
		while(SensorValue[bump] == 0 && activated){
			reverse = true;
			activated = false;
		}

		if(activated == true){
			motor[leftMotor] = 63;
			motor[rightMotor] = 63;
			
		}
		if(reverse){
				//activated = false;
				reverse = false;
				motor[leftMotor] = -63;
				motor[rightMotor] = -63;
				wait1Msec(3500);
		}
		
	}

}*/
task main(){
	
	bool forward = false;
	
	while(SensorValue[bump] == 1){}
	
	while(SensorValue[bump] == 0){
		forward = true;
		wait1Msec(10);
	}
	
	while(forward){
		motor[leftMotor] = 63;
		motor[rightMotor] = 63;
		//wait1Msec(1000);
		if(SensorValue[bump] == 0){
			forward = false;
		}
	}
	
	motor[leftMotor] = -63;
	motor[rightMotor] = -63;
	
	wait10Msec(350);



}
