#pragma config(Sensor, dgtl1,  button,         sensorTouch)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//graph of distance vs times can be found at https://www.desmos.com/calculator/oki7aqrys9

void wait(int len){
	wait1Msec(len);
}

void move(int length, int dir){

	//dir controls direction. Positive value goes forward, negative value goes backwards.
	//k is some constant which relates distance traveled to time in units of s/cm
	float k = 20.243; //21.739
	float b = 371.54;
	int time = length * k + b;
	int speedl = 58;//sgn((float) dir) * 58;
	int speedr = 46;//sgn((float) dir) * 46;

	motor[leftMotor] = speedl;
	motor[rightMotor] = speedr;
	wait1Msec(time);
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	
	wait(1000);
}

void turn90(int dir){

	//change time depending on how long it actually takes to make a right turn;
	//positive dir makes a right turn, negative makes a left turn;
	int time = 800;
	int speedl = 58;//sgn((float) dir) * 58;
	int speedr = 46;//sgn((float) dir) * 46;
	
	if(dir > 0){
		motor[leftMotor] = speedl;
		motor[rightMotor] = -speedr;
		wait1Msec(time);
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
	}
	if(dir < 0){
		motor[rightMotor] = speedr;
		motor[leftMotor] = -speedl;
		wait1Msec(time);
		motor[rightMotor] = 0;
		motor[leftMotor] = 0;
	}

	wait(1000);

}

task main(){

	while(SensorValue[button] == 0){}
	
	move(150, 1);
	/*
	int time = 1500;
	move(time, 1);
	turn90(-1);
	move(time, 1);
	turn90(-1);
	move(time, 1);
	turn90(-1);
	move(time, 1);
	*/

}
